name: pet_core
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pet_presentation:
    path : ./pet_presentation
  
  
  


  # cupertino_icons: ^1.0.2
  # flutter_form_builder: ^7.1.1
  # form_builder_validators: ^7.7.0
  # go_router: ^3.0.4
  # get: ^4.1.4
  # wave: ^0.2.0
  # intl: ^0.17.0
  # flutter_localizations:
  #   sdk: flutter
  
  # freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # intl_utils:
  build_runner: "^2.1.7"
  # flutter_gen_runner: "4.1.5"
  # freezed: ^1.1.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  

