name: pet_project_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  go_router: ^3.0.4
  get: ^4.1.4
  wave: ^0.2.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  freezed_annotation: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils:
  build_runner: "^2.1.7"
  flutter_gen_runner: "4.1.5"
  freezed: ^1.1.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated/
  use_deferred_loading: false
    

  