name: pet_data
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pet_domain:
    path: ../pet_domain
  # google_sign_in: '^4.5.1'
  firebase_auth: ^4.1.2
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.3
  cloud_firestore: ^4.0.5
  collection: ^1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "^2.1.7"
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  