name: pet_presentation
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^3.0.7
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  intl_utils:
  build_runner: "^2.1.7"
  flutter_gen_runner: "4.1.5"
  freezed: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated/
  use_deferred_loading: false
