name: pet_presentation
description: A new Flutter package project.
version: 0.0.1

publish_to: 'none' 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pet_domain:
    path: ../pet_domain
  pet_data:
    path: ../pet_data
  go_router: ^3.0.7
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  badges: ^2.0.3
  freezed_annotation:
  modal_bottom_sheet: ^2.1.0 
  after_layout: ^1.2.0
  clay_containers: ^0.3.2
  auto_size_text: ^3.0.0
  equatable: ^2.0.3
  flutter_svg: ^1.1.1+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  flutter_lints: ^1.0.0
  intl_utils:
  build_runner: "^2.1.7"
  flutter_gen_runner: "4.1.5"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  null_safety: true # Optional (default: true)
  output: lib/generated/ # Optional (default: lib/gen/)
  integrations:
    flutter_svg: true
    # flare_flutter: true
  assets:
    enable: true
    package_parameter_enabled: true
    
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated/
  use_deferred_loading: false
